Update update_translations.yaml

diff --git a/.github/workflows/update_translations.yaml b/.github/workflows/update_translations.yaml
--- a/.github/workflows/update_translations.yaml
+++ b/.github/workflows/update_translations.yaml
@@ -32,26 +32,28 @@ jobs:
                   curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/LibreScore/repos?per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | sed -e 's/^git:\/\//https:\/\/${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }}@/g' | xargs -I {} bash -c "if [[ {} =~ /(docs|dl-librescore|app-librescore|webmscore-pwa).git$ ]]; then git -C $HOME/repos clone {} --single-branch --no-tags --depth=1 ; fi"
                   rm -R -f $HOME/repos/*/docs
                   rm -R -f $HOME/repos/docs/i18n
-                  mv -f $HOME/repos/docs/source/titles $HOME/repos/titles
+                  mv -f $HOME/repos/docs/source/titles $HOME/repos/titles || echo "failed=true" >> $GITHUB_ENV
                   rm -R -f $HOME/repos/docs/source
                   find $HOME/repos -not -path "$HOME/repos/titles/*" ! -name "*.md" -type f -delete
                   find $HOME/repos -not -path "$HOME/repos/titles/*" -type d -empty -delete
             - uses: actions/checkout@v3
+              if: env.failed != 'true'
             - name: Generate translations
+              if: env.failed != 'true'
               run: |
                   rm -R -f source/*
                   mv -f $HOME/repos/* source/
                   rm -R -f $HOME/repos
                   /bin/bash ./po4a.sh
             - name: Push to current repo
+              if: env.failed != 'true'
               run: |
-                  updated=0
                   mkdir -p ./docs
                   rm -R -f ./docs/*
                   cp -a ./i18n/docs/* ./docs/ -v
                   cp -a ./i18n/docs/en/* . -v
                   if [[ -n $(git status -z --porcelain ./i18n) ]]; then
-                      updated=1
+                      echo "updated=true" >> $GITHUB_ENV
                       git config user.name github-actions
                       git config user.email github-actions@github.com
                       git add -A
@@ -61,6 +63,7 @@ jobs:
                       curl -s -d '{"lock":"false"}' -H "Content-Type: application/json" -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" https://librescore.ddns.net/api/components/librescore/docs/lock/
                   fi
             - name: Push to remote repos
+              if: env.failed != 'true'
               run: |
                   shopt -s nullglob
                   for dir in i18n/*/ ; do
@@ -75,7 +78,7 @@ jobs:
                           cp -a $dir/en/* $HOME/$repo/ -v
                           cd $HOME/$repo
                           if [[ -n $(git status -z --porcelain) ]]; then
-                              updated=1
+                              echo "updated=true" >> $GITHUB_ENV
                               git config user.name github-actions
                               git config user.email github-actions@github.com
                               git add -A
@@ -88,6 +91,7 @@ jobs:
                       fi
                   done
                   shopt -u nullglob
-                  if [[ $updated -eq 0 ]]; then
-                      curl -s -i -u ${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }} -d '{"event_type":"delete_action","client_payload":{"run_id":"'"${{ github.run_id }}"'","repo":"LibreScore/docs"}}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/actions/dispatches
-                  fi
+            - name: Delete workflow run
+              if: env.updated != 'true'
+              run: |
+                curl -s -i -u ${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }} -d '{"event_type":"delete_action","client_payload":{"run_id":"'"${{ github.run_id }}"'","repo":"LibreScore/docs"}}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/actions/dispatches
